In [ ]:
import pandas as pd
from runeq import initialize
# Pull your rune authentication yaml from ~/.rune/config (C:\Users\<USERNAME>>\.rune\config on Windows)
initialize()

In [35]:
# To see information about your authenticated user
from runeq.resources.user import get_current_user 
my_user = get_current_user()
print(my_user) 
print('ActiveOrg:',my_user.active_org_name)

User(id="user-ec4556eb2df55e2ff5c4535c9cab64b2c75c4019,user", name="None")
ActiveOrg: OPTiMaL Project

In [36]:
# Get all the available patients and all the devices for each patient
from runeq.resources.patient import get_all_patients
patients = get_all_patients()
a_device = None
for patient in patients: 
    print(patient)
    for device in patient.devices: 
        a_device = device
        print(' ',device)

Patient(id="rcs07", name="RCS07")
  Device(id="xunPq7qF", name="StriveStudy Left", patient_id="rcs07")
  Device(id="RElEtNme", name="Apple Watch Right (OLD)", patient_id="rcs07")
  Device(id="mn69eHPB", name="Apple Watch Right 011823", patient_id="rcs07")
  Device(id="Ci8uqRFf", name="Strive PD", patient_id="rcs07")
  Device(id="GNmN5Ps_", name="Apple Watch Left 011823", patient_id="rcs07")
  Device(id="0Z48CCdv", name="Apple Watch Left (OLD)", patient_id="rcs07")
  Device(id="476fcJDJ", name="StriveStudy Right", patient_id="rcs07")
  Device(id="EQkHRl_j", name="StriveStudy Left", patient_id="rcs07")
  Device(id="8QuY9OFb", name="Apple Watch Left", patient_id="rcs07")
  Device(id="zfVoAXlX", name="Strive PD Right 01.18.22", patient_id="rcs07")
  Device(id="NPC700403H", name="RC+S Right", patient_id="rcs07")
  Device(id="NPC700419H", name="RC+S Left", patient_id="rcs07")
  Device(id="fn1Ww9vP", name="Strive PD Left 01.18.22", patient_id="rcs07")
  Device(id="Om3Cm3Kz", name="Apple Watch Right", patient_id="rcs07")
  Device(id="U_xlWbXm", name="StriveStudy Left", patient_id="rcs07")

In [37]:
a_device.patient_id

'rcs07'

In [38]:
# Get the streams available for a particular patient
from runeq.resources.stream_metadata import get_patient_stream_metadata
patient_id = 'rcs07'
patient_streams = get_patient_stream_metadata(patient_id)
print(f'Found {len(patient_streams)} total streams')
stream_df = patient_streams.to_dataframe()
display(stream_df)

categories = stream_df['category'].unique().tolist()
print(f'Found the following categories of streams: \n  {categories}')

Found 311 total streams

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,log_type,measurement,id,severity,axis,source_device,function,hk_aggregation
0,1.677297e+09,ingest-rune-events.0,0Z48CCdv,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.642695e+09,1.645120e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,stop,watch_recording_manual,32bb76f4d67e758a85308fd1fa154f4f88f8cb0d6c0349...,NaN,NaN,NaN,NaN,NaN
1,1.677308e+09,ingest-rune-events.0,0Z48CCdv,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.642581e+09,1.645814e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,start,watch_recording_manual,2c81d8582eeb3aabcb0efe3af6abc063f7a2b17e9aa674...,NaN,NaN,NaN,NaN,NaN
2,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,NaN,tremor,d382ad670ae5c715dd4444b89a6ee808baa93a760e85bc...,none,NaN,NaN,NaN,NaN
3,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,NaN,tremor,f548ba2c90ef848cb609ebc079364c43687f2ca65df9b9...,mild,NaN,NaN,NaN,NaN
4,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,NaN,tremor,44f04f8dc5a93e7878bc6fa06cf0741af808cab52a0b3e...,unknown,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Rate per minute', 'description': 'Ra...",1.674082e+09,1.688421e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate,72a7f4e117413c6b9fb2d79190b696e9c827ef44d290b3...,NaN,NaN,apple_watch,NaN,NaN
307,1.701264e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Rate per minute', 'description': 'Ra...",1.680200e+09,1.685037e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate_resting,0447d4eed06a581d23727191447e82382fbf03aced07e9...,NaN,NaN,apple_health,NaN,NaN
308,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Speed', 'description': 'Speed, sampl...",1.679622e+09,1.684442e+09,"{'category': 'motion', 'measurement': 'stair_d...",motion,NaN,stair_descent_speed,37ef41600f9da5dbaa0fa17472735397ad5488198bbaf5...,NaN,NaN,apple_health,NaN,NaN
309,1.701264e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Speed', 'description': 'Speed, sampl...",1.680205e+09,1.684442e+09,"{'category': 'motion', 'measurement': 'stair_a...",motion,NaN,stair_ascent_speed,e1d76e69aac7072b41ec6c9ac6fb2c9391a4bbc7df8aa8...,NaN,NaN,apple_health,NaN,NaN
310,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'State', 'description': 'Current stat...",1.674082e+09,1.688421e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate_motion_context,36e919adc4083f5bea6add12ed730c7145febe12892a3e...,NaN,NaN,apple_watch,NaN,NaN

Found the following categories of streams:
  ['patient_report', 'symptom', 'motion', 'vitals', 'device_info']

In [ ]:
# Look at the more specific attributes of the motion-related streams
grav_streams = patient_streams.filter(category='motion', measurement='gravity')
display(grav_streams.to_dataframe())

In [ ]:
# Make a function for more customizable filtering of the available streams
from runeq.resources.stream_metadata import get_stream_metadata, get_stream_availability_dataframe
stream_meta = get_stream_metadata(list(grav_streams.ids())[0])

def is_x_stream(stream):
    return 'axis' in stream.parameters.keys() and stream.parameters['axis'] in ['x'] # , 'y', 'z']


x_streams = patient_streams.filter(filter_function=is_x_stream, measurement='user')
display(x_streams.to_dataframe())

# Get available times for May 4, 2023
try:
    available = x_streams.get_batch_availability_dataframe(
        start_time=1681408661, end_time=1681427545, timezone=-28800,
        batch_operation='any', resolution=60*15)
except Exception as e:
    print(e)
else:
    display(available)

In [ ]:
import numpy as np
from runeq.resources.patient import get_device
# Get a list of devices with data available on a given day:
date = pd.Timestamp(1681427545, unit='s', tz='US/Pacific')
end_of_day = date + pd.Timedelta(hours=4)
resolution = 300

cumulative_avail = {}
for device in patient_streams.to_dataframe()['device_id'].unique():
    device_streams = x_streams.filter(device_id=device)
    try:
        device_avail = device_streams.get_batch_availability_dataframe(
            start_time=int(date.timestamp()), end_time=int(end_of_day.timestamp()), timezone=-28800,
            resolution=resolution, batch_operation='any'
        )
    except Exception as e:
        print(f'Device {device}')
        print(f'    {e}')
    else:
        # There is some data available for this device
        if sum(device_avail['availability']) > 0:
            print(f'Found data for {device}: {get_device(patient, device).name}')
            cumulative_avail[device] = device_avail
        else:
            print(f'No data for {device}')

In [ ]:
# Given the devices from above, find the range of times with available data
if len(cumulative_avail):
    devices = list(cumulative_avail.keys())
    raw_avail = [df['availability'].to_numpy() for df in cumulative_avail.values()]
    cumulative = [np.sum(raw_avail, axis=0) >= 1][0]
    avail_times = (cumulative_avail[devices[0]]['time'][cumulative]).to_numpy()
    start, end = int(pd.Timestamp(avail_times[0]).timestamp()), int(pd.Timestamp(avail_times[-1]).timestamp()) + resolution
    print(f'Data for {devices} available between {start} and {end}')
else:
    print('NO DATA FOUND IN THE GIVEN TIME RANGE!')

In [39]:
# Get the data for the available time range
desired_ids = devices

all_data = []
for device in desired_ids:
    desired_streams = get_patient_stream_metadata('rcs07', device) # .filter(category='motion')
    print(f'Data for {device}: {get_device(patient, device).name}')
    print(f'Found {len(list(desired_streams.ids()))} streams over {(end - start) / 60} minutes.')
    # for stream_id in desired_streams.ids():
    #     stream = get_stream_metadata(stream_id,)
    #     print(f'Fetching: {stream.parameters}')
    #     stream_data = stream.get_stream_dataframe(
    #         start_time=start, end_time=end
    #     )
    #     all_data.append(stream_data)

Data for GNmN5Ps_: Apple Watch Left 011823
Found 26 streams over 5.0 minutes.
Data for mn69eHPB: Apple Watch Right 011823
Found 27 streams over 5.0 minutes.

In [40]:
desired_streams.to_dataframe()

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,measurement,id,log_type,severity,axis
0,1.682662e+09,ingest-rune-events.0,mn69eHPB,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.682661e+09,1.682661e+09,"{'category': 'patient_report', 'measurement': ...",patient_report,watch_recording_stop_low_battery,a357d0cc64293975d2a4b93f03482a9878dbfcdff5647d...,NaN,NaN,NaN
1,1.676579e+09,ingest-rune-events.0,mn69eHPB,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.674082e+09,1.677781e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,watch_recording_manual,32ae6f2f037e96f31df66d68d2e759b753f823565e944d...,start,NaN,NaN
2,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'moderate'...",symptom,tremor,ecd8f5ea4a9ca1f6650879ca18bb3d9905b5e31139811d...,NaN,moderate,NaN
3,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'all', 'me...",symptom,tremor,f6e1b9abc9c83c553b53220ef4b490b80a239e437ed55d...,NaN,all,NaN
4,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,bdfbe75dde014c71d1749713c05653315b3bf2872771b0...,NaN,unknown,NaN
5,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,e62e732570bfff24bcdf8a9f6779834f54de7a45ddc06d...,NaN,NaN,NaN
6,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,4cded6ba90577ec63cbcf09400ce53d94f00700f6a0b92...,NaN,mild,NaN
7,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,0b23cf09421e01b46a802f6521b4061a5e1674a6a1a31d...,NaN,strong,NaN
8,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'slight', ...",symptom,tremor,0cea5ee2938b233f4c44d38e13d3fd3647df3452f1cc56...,NaN,slight,NaN
9,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,0e6e5b1ad8946624af43cfb4e74424a036d4eac2e51832...,NaN,none,NaN
10,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'moderate'...",symptom,tremor,f530d041ce3c31cfab23ebe04b2d12f53694ca5ca24bd5...,NaN,moderate,NaN
11,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'all', 'me...",symptom,tremor,8dfdc7abcf0cd6b56735cbdb709f22a5ed8a4c7540f2da...,NaN,all,NaN
12,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,c0978fac4f335f455db7ca85de80245791c60ea00ac4ec...,NaN,unknown,NaN
13,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,eae0a1d7c4b84a90bb42db7d1ed4f1b8111adf24563982...,NaN,NaN,NaN
14,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,cf8b6f2edec1732bf32caa8eab106db0faed632103a297...,NaN,none,NaN
15,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,7293805ba85e11d59399f6de14dfe62f6a794467660894...,NaN,strong,NaN
16,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,8bc50566661e4a7bb48fe2d3da659e62d925193dbb80a5...,NaN,mild,NaN
17,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'slight', ...",symptom,tremor,e32d8d47637ca64cd7723a2792769a3f988ed25920c0de...,NaN,slight,NaN
18,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",motion,user,9f0e8149201e6eda540ae6d0d060e79dca2e8ecb149d56...,NaN,NaN,y
19,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",motion,gravity,0dc5b6c50ea389a4d90c6ef88a284f674e37d4d5b6f158...,NaN,NaN,y
20,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",motion,gravity,c6dd49ba9bb7c545067bdf55338c0f0694a5229c98330b...,NaN,NaN,x
21,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",motion,user,adb411995e64ec3540e53eba88b566304fe94725296840...,NaN,NaN,x
22,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",motion,gravity,3edf20fbc7ebd3c5db0fae47abc14e3eb00e9534958cf9...,NaN,NaN,z
23,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",motion,user,7857f79ec09b690a2f2393091d251aa0b19d0b21af9443...,NaN,NaN,z
24,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion'}",motion,NaN,b53d28bb7af688135f21843f6ccd60c97a73a3693323c4...,NaN,NaN,x
25,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion'}",motion,NaN,0be95dfbf640adb9678a1f664bf60f4c64f8ac7536c2bf...,NaN,NaN,y
26,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion'}",motion,NaN,ff595d0057a87e6f9ef73769bb8b6a9a15e6e27ef408ed...,NaN,NaN,z

In [43]:
stream = get_stream_metadata(list(desired_streams.ids())[0])