In [1]:
import pandas as pd
from runeq import initialize
# Pull your rune authentication yaml from ~/.rune/config (C:\Users\<USERNAME>>\.rune\config on Windows)
initialize()

In [2]:
# To see information about your authenticated user
from runeq.resources.user import get_current_user 
my_user = get_current_user()
print(my_user) 
print('ActiveOrg:',my_user.active_org_name)

User(id="user-95316bb8df0035fb4794b9c40da74c2737a2661d,user", name="Thomas Kutcher")
ActiveOrg: Baylor - TRD

In [3]:
# Get all the available patients and all the devices for each patient
from runeq.resources.patient import get_all_patients
patients = get_all_patients()
a_device = None
for patient in patients: 
    print(patient)
    for device in patient.devices: 
        a_device = device
        print(' ',device)

Patient(id="b79e9da25bd048008322a1d8d185fccd", name="Sai Test")
  Device(id="fpO2V9Y2", name="Apple Watch", patient_id="b79e9da25bd048008322a1d8d185fccd")
  Device(id="iU1bD*DQ", name="StrivePD", patient_id="b79e9da25bd048008322a1d8d185fccd")
  Device(id="113Z*c4H", name="StrivePD", patient_id="b79e9da25bd048008322a1d8d185fccd")
  Device(id="uH_IKv2X", name="Apple Watch", patient_id="b79e9da25bd048008322a1d8d185fccd")
Patient(id="c2e72a4bc7004b19be199ab5c325bcfd", name="Thomas Test")
  Device(id="qVQ245Mn", name="StrivePD", patient_id="c2e72a4bc7004b19be199ab5c325bcfd")
  Device(id="5QKVqRiL", name="Apple Watch", patient_id="c2e72a4bc7004b19be199ab5c325bcfd")

In [37]:
a_device.patient_id

'rcs07'

In [ ]:
# Get the streams available for a particular patient
from runeq.resources.stream_metadata import get_patient_stream_metadata
patient_id = 'c2e72a4bc7004b19be199ab5c325bcfd'
patient_streams = get_patient_stream_metadata(patient_id)
print(f'Found {len(patient_streams)} total streams')
stream_df = patient_streams.to_dataframe()
display(stream_df)

categories = stream_df['category'].unique().tolist()
print(f'Found the following categories of streams: \n  {categories}')

Found 137 total streams

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,measurement,id,severity,sleep_status,source_device,user_entered,function,log_type
0,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,NaN,NaN,NaN,NaN,NaN,NaN
1,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,c3e4b2f20171302f02e06efcdfdbcbb3084a436f7ca2a8...,none,NaN,NaN,NaN,NaN,NaN
2,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,1960d0ebfef57daae44de462ddcf574700b26781bdaa17...,strong,NaN,NaN,NaN,NaN,NaN
3,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,b1e6100fb43e98f7f54800adc50557634fb2bee05f4985...,mild,NaN,NaN,NaN,NaN,NaN
4,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,c9f37ff1809d930e5ffa5e1d97ff40f70b9530cb1a0db1...,unknown,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,1.730669e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.700889e+09,1.702912e+09,"{'category': 'sleep', 'measurement': 'sleep_st...",sleep,sleep_stage,05a7a201133d87a5cc0b734add5273e277f66a2a47bad4...,NaN,NaN,apple_health,NaN,NaN,NaN
133,1.729799e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.624286e+09,1.739203e+09,"{'category': 'device_info', 'measurement': 'de...",device_info,device_placement,fc719eb53d4cb61a628e00da088d847f3e9a26b70bc72e...,NaN,NaN,iphone,NaN,NaN,NaN
134,1.729795e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.700876e+09,1.739210e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,heart_rate_motion_context,f8622539fad5f9d7a7c7a8701684e990f020ecf93e4af5...,NaN,NaN,apple_watch,NaN,NaN,NaN
135,1.734663e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.734413e+09,1.739195e+09,"{'category': 'sleep', 'measurement': 'sleep_st...",sleep,sleep_stage,9d09e432491350f23426474ecc5c2c1d4778d56d43f0cc...,NaN,NaN,oura,NaN,NaN,NaN
136,1.729799e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Timezone', 'description': 'Timezone,...",1.672979e+09,1.731380e+09,"{'category': 'environment', 'measurement': 'ut...",environment,utc_offset,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,NaN,NaN,apple_health,NaN,NaN,NaN

Found the following categories of streams:
  ['symptom', 'sleep', 'motion', 'vitals', 'device_info', 'environment']

In [11]:
stream_df['date_end'] = pd.to_datetime(stream_df['max_time'], unit='s').dt.strftime('%Y-%m-%d')
date_end = stream_df['date_end'].unique().tolist()
print(f'Found the following categories of streams (end): \n  {date_end}')

stream_df['date_start'] = pd.to_datetime(stream_df['min_time'], unit='s').dt.strftime('%Y-%m-%d')
date_start = stream_df['date_start'].unique().tolist()
print(f'Found the following categories of streams (start): \n  {date_start}')

stream_df['date_create'] = pd.to_datetime(stream_df['created_at'], unit='s').dt.strftime('%Y-%m-%d')
date_create = stream_df['date_create'].unique().tolist()
print(f'Found the following categories of streams (create): \n  {date_create}')

print(stream_df['source_device'].unique().tolist())

display(stream_df)

Found the following categories of streams (end):
  ['2025-01-23', '2025-02-10', '2024-11-12', '2023-12-18', '2023-11-25', '2025-01-14', '2025-01-30', '2025-02-11']
Found the following categories of streams (start):
  ['2024-10-23', '2024-12-17', '2023-01-06', '2023-11-25', '2021-06-19', '2024-12-16', '2021-06-21', '2021-06-20', '2021-11-11']
Found the following categories of streams (create):
  ['2024-10-23', '2024-12-20', '2024-10-24', '2024-11-03', '2024-11-04']
[nan, 'oura', 'apple_health', 'iphone', 'apple_watch', 'unspecified']

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,measurement,...,severity,sleep_status,source_device,user_entered,function,log_type,date,date_end,date_start,date_create
0,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,2025-01-23,2025-01-23,2024-10-23,2024-10-23
1,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,...,none,NaN,NaN,NaN,NaN,NaN,2025-01-23,2025-01-23,2024-10-23,2024-10-23
2,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,...,strong,NaN,NaN,NaN,NaN,NaN,2025-01-23,2025-01-23,2024-10-23,2024-10-23
3,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,...,mild,NaN,NaN,NaN,NaN,NaN,2025-01-23,2025-01-23,2024-10-23,2024-10-23
4,1.729706e+09,ingest-strive-applewatch-md.0,5QKVqRiL,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Duration', 'description': 'Durations...",1.729705e+09,1.737653e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,...,unknown,NaN,NaN,NaN,NaN,NaN,2025-01-23,2025-01-23,2024-10-23,2024-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,1.730669e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.700889e+09,1.702912e+09,"{'category': 'sleep', 'measurement': 'sleep_st...",sleep,sleep_stage,...,NaN,NaN,apple_health,NaN,NaN,NaN,2023-12-18,2023-12-18,2023-11-25,2024-11-03
133,1.729799e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.624286e+09,1.739203e+09,"{'category': 'device_info', 'measurement': 'de...",device_info,device_placement,...,NaN,NaN,iphone,NaN,NaN,NaN,2025-02-10,2025-02-10,2021-06-21,2024-10-24
134,1.729795e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.700876e+09,1.739210e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,heart_rate_motion_context,...,NaN,NaN,apple_watch,NaN,NaN,NaN,2025-02-10,2025-02-10,2023-11-25,2024-10-24
135,1.734663e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'State', 'description': 'Current stat...",1.734413e+09,1.739195e+09,"{'category': 'sleep', 'measurement': 'sleep_st...",sleep,sleep_stage,...,NaN,NaN,oura,NaN,NaN,NaN,2025-02-10,2025-02-10,2024-12-17,2024-12-20
136,1.729799e+09,ingest-strive-healthkit.1,qVQ245Mn,c2e72a4bc7004b19be199ab5c325bcfd,"{'name': 'Timezone', 'description': 'Timezone,...",1.672979e+09,1.731380e+09,"{'category': 'environment', 'measurement': 'ut...",environment,utc_offset,...,NaN,NaN,apple_health,NaN,NaN,NaN,2024-11-12,2024-11-12,2023-01-06,2024-10-24

In [10]:
df = patient_streams.get_stream_dataframe()
display(df)

/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)
/opt/miniconda3/lib/python3.12/site-packages/runeq/resources/stream_metadata.py:408: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  stream_df = pd.concat(all_stream_dfs, axis=0, ignore_index=True)

,time,duration,measurement_duration_ns,stream_id,stream_type_id,patient_id,device_id,algorithm,category,measurement,...,rpm,start_time_min,start_time,end_time,end_time_max,event,speed,state,timezone_offset,log_type
0,2024-10-23T17:30:00Z,0.0,60000000000,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,duration,c2e72a4bc7004b19be199ab5c325bcfd,5QKVqRiL,ingest-strive-applewatch-md.0,symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-10-23T17:31:00Z,0.0,60000000000,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,duration,c2e72a4bc7004b19be199ab5c325bcfd,5QKVqRiL,ingest-strive-applewatch-md.0,symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-10-23T17:32:00Z,0.0,60000000000,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,duration,c2e72a4bc7004b19be199ab5c325bcfd,5QKVqRiL,ingest-strive-applewatch-md.0,symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-10-23T17:33:00Z,0.0,60000000000,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,duration,c2e72a4bc7004b19be199ab5c325bcfd,5QKVqRiL,ingest-strive-applewatch-md.0,symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-10-23T17:34:00Z,0.0,60000000000,cd9527c2ab276f7b60be8d9090c79efac48c2acdda26cf...,duration,c2e72a4bc7004b19be199ab5c325bcfd,5QKVqRiL,ingest-strive-applewatch-md.0,symptom,dyskinesia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2762896,2024-11-08T03:28:02Z,NaN,34320986892000,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,timezone,c2e72a4bc7004b19be199ab5c325bcfd,qVQ245Mn,ingest-strive-healthkit.1,environment,utc_offset,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64800,NaN
2762897,2024-11-09T04:21:45Z,NaN,31095927454000,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,timezone,c2e72a4bc7004b19be199ab5c325bcfd,qVQ245Mn,ingest-strive-healthkit.1,environment,utc_offset,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64800,NaN
2762898,2024-11-10T03:09:48Z,NaN,35414755755000,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,timezone,c2e72a4bc7004b19be199ab5c325bcfd,qVQ245Mn,ingest-strive-healthkit.1,environment,utc_offset,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64800,NaN
2762899,2024-11-11T03:33:04Z,NaN,34018644744900,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,timezone,c2e72a4bc7004b19be199ab5c325bcfd,qVQ245Mn,ingest-strive-healthkit.1,environment,utc_offset,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64800,NaN
2762900,2024-11-12T03:00:00Z,NaN,36000072187000,26e5dc8df5803bfa0e2928926de3bd4771b54c378a0630...,timezone,c2e72a4bc7004b19be199ab5c325bcfd,qVQ245Mn,ingest-strive-healthkit.1,environment,utc_offset,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,64800,NaN

In [ ]:
# Look at the more specific attributes of the motion-related streams
grav_streams = patient_streams.filter(category='motion', measurement='gravity')
display(grav_streams.to_dataframe())

In [ ]:
# Make a function for more customizable filtering of the available streams
from runeq.resources.stream_metadata import get_stream_metadata, get_stream_availability_dataframe
stream_meta = get_stream_metadata(list(grav_streams.ids())[0])

def is_x_stream(stream):
    return 'axis' in stream.parameters.keys() and stream.parameters['axis'] in ['x'] # , 'y', 'z']


x_streams = patient_streams.filter(filter_function=is_x_stream, measurement='user')
display(x_streams.to_dataframe())

# Get available times for May 4, 2023
try:
    available = x_streams.get_batch_availability_dataframe(
        start_time=1681408661, end_time=1681427545, timezone=-28800,
        batch_operation='any', resolution=60*15)
except Exception as e:
    print(e)
else:
    display(available)

In [ ]:
import numpy as np
from runeq.resources.patient import get_device
# Get a list of devices with data available on a given day:
date = pd.Timestamp(1681427545, unit='s', tz='US/Pacific')
end_of_day = date + pd.Timedelta(hours=4)
resolution = 300

cumulative_avail = {}
for device in patient_streams.to_dataframe()['device_id'].unique():
    device_streams = x_streams.filter(device_id=device)
    try:
        device_avail = device_streams.get_batch_availability_dataframe(
            start_time=int(date.timestamp()), end_time=int(end_of_day.timestamp()), timezone=-28800,
            resolution=resolution, batch_operation='any'
        )
    except Exception as e:
        print(f'Device {device}')
        print(f'    {e}')
    else:
        # There is some data available for this device
        if sum(device_avail['availability']) > 0:
            print(f'Found data for {device}: {get_device(patient, device).name}')
            cumulative_avail[device] = device_avail
        else:
            print(f'No data for {device}')

In [ ]:
# Given the devices from above, find the range of times with available data
if len(cumulative_avail):
    devices = list(cumulative_avail.keys())
    raw_avail = [df['availability'].to_numpy() for df in cumulative_avail.values()]
    cumulative = [np.sum(raw_avail, axis=0) >= 1][0]
    avail_times = (cumulative_avail[devices[0]]['time'][cumulative]).to_numpy()
    start, end = int(pd.Timestamp(avail_times[0]).timestamp()), int(pd.Timestamp(avail_times[-1]).timestamp()) + resolution
    print(f'Data for {devices} available between {start} and {end}')
else:
    print('NO DATA FOUND IN THE GIVEN TIME RANGE!')

In [39]:
# Get the data for the available time range
desired_ids = devices

all_data = []
for device in desired_ids:
    desired_streams = get_patient_stream_metadata('rcs07', device) # .filter(category='motion')
    print(f'Data for {device}: {get_device(patient, device).name}')
    print(f'Found {len(list(desired_streams.ids()))} streams over {(end - start) / 60} minutes.')
    # for stream_id in desired_streams.ids():
    #     stream = get_stream_metadata(stream_id,)
    #     print(f'Fetching: {stream.parameters}')
    #     stream_data = stream.get_stream_dataframe(
    #         start_time=start, end_time=end
    #     )
    #     all_data.append(stream_data)

Data for GNmN5Ps_: Apple Watch Left 011823
Found 26 streams over 5.0 minutes.
Data for mn69eHPB: Apple Watch Right 011823
Found 27 streams over 5.0 minutes.

In [40]:
desired_streams.to_dataframe()

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,measurement,id,log_type,severity,axis
0,1.682662e+09,ingest-rune-events.0,mn69eHPB,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.682661e+09,1.682661e+09,"{'category': 'patient_report', 'measurement': ...",patient_report,watch_recording_stop_low_battery,a357d0cc64293975d2a4b93f03482a9878dbfcdff5647d...,NaN,NaN,NaN
1,1.676579e+09,ingest-rune-events.0,mn69eHPB,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.674082e+09,1.677781e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,watch_recording_manual,32ae6f2f037e96f31df66d68d2e759b753f823565e944d...,start,NaN,NaN
2,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'moderate'...",symptom,tremor,ecd8f5ea4a9ca1f6650879ca18bb3d9905b5e31139811d...,NaN,moderate,NaN
3,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'all', 'me...",symptom,tremor,f6e1b9abc9c83c553b53220ef4b490b80a239e437ed55d...,NaN,all,NaN
4,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,bdfbe75dde014c71d1749713c05653315b3bf2872771b0...,NaN,unknown,NaN
5,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,e62e732570bfff24bcdf8a9f6779834f54de7a45ddc06d...,NaN,NaN,NaN
6,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,4cded6ba90577ec63cbcf09400ce53d94f00700f6a0b92...,NaN,mild,NaN
7,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,0b23cf09421e01b46a802f6521b4061a5e1674a6a1a31d...,NaN,strong,NaN
8,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'slight', ...",symptom,tremor,0cea5ee2938b233f4c44d38e13d3fd3647df3452f1cc56...,NaN,slight,NaN
9,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,0e6e5b1ad8946624af43cfb4e74424a036d4eac2e51832...,NaN,none,NaN
10,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'moderate'...",symptom,tremor,f530d041ce3c31cfab23ebe04b2d12f53694ca5ca24bd5...,NaN,moderate,NaN
11,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'all', 'me...",symptom,tremor,8dfdc7abcf0cd6b56735cbdb709f22a5ed8a4c7540f2da...,NaN,all,NaN
12,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,tremor,c0978fac4f335f455db7ca85de80245791c60ea00ac4ec...,NaN,unknown,NaN
13,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'measurement': 'dyskin...",symptom,dyskinesia,eae0a1d7c4b84a90bb42db7d1ed4f1b8111adf24563982...,NaN,NaN,NaN
14,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,tremor,cf8b6f2edec1732bf32caa8eab106db0faed632103a297...,NaN,none,NaN
15,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'strong', ...",symptom,tremor,7293805ba85e11d59399f6de14dfe62f6a794467660894...,NaN,strong,NaN
16,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,tremor,8bc50566661e4a7bb48fe2d3da659e62d925193dbb80a5...,NaN,mild,NaN
17,1.674083e+09,ingest-strive-applewatch-md.0,mn69eHPB,rcs07,"{'name': 'Percentage', 'description': 'Percent...",1.674082e+09,1.685057e+09,"{'category': 'symptom', 'severity': 'slight', ...",symptom,tremor,e32d8d47637ca64cd7723a2792769a3f988ed25920c0de...,NaN,slight,NaN
18,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",motion,user,9f0e8149201e6eda540ae6d0d060e79dca2e8ecb149d56...,NaN,NaN,y
19,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",motion,gravity,0dc5b6c50ea389a4d90c6ef88a284f674e37d4d5b6f158...,NaN,NaN,y
20,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",motion,gravity,c6dd49ba9bb7c545067bdf55338c0f0694a5229c98330b...,NaN,NaN,x
21,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",motion,user,adb411995e64ec3540e53eba88b566304fe94725296840...,NaN,NaN,x
22,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",motion,gravity,3edf20fbc7ebd3c5db0fae47abc14e3eb00e9534958cf9...,NaN,NaN,z
23,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",motion,user,7857f79ec09b690a2f2393091d251aa0b19d0b21af9443...,NaN,NaN,z
24,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion'}",motion,NaN,b53d28bb7af688135f21843f6ccd60c97a73a3693323c4...,NaN,NaN,x
25,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion'}",motion,NaN,0be95dfbf640adb9678a1f664bf60f4c64f8ac7536c2bf...,NaN,NaN,y
26,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Rotation', 'description': 'Rotation ...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion'}",motion,NaN,ff595d0057a87e6f9ef73769bb8b6a9a15e6e27ef408ed...,NaN,NaN,z

In [43]:
stream = get_stream_metadata(list(desired_streams.ids())[0])