In [1]:
import pandas as pd
from runeq import initialize
# Pull your rune authentication yaml from ~/.rune/config (C:\Users\<USERNAME>>\.rune\config on Windows)
initialize()

In [2]:
# To see information about your authenticated user
from runeq.resources.user import get_current_user 
my_user = get_current_user()
print(my_user) 
print('ActiveOrg:',my_user.active_org_name)

User(id="user-ec4556eb2df55e2ff5c4535c9cab64b2c75c4019,user", name="None")
ActiveOrg: OPTiMaL Project

In [3]:
# Get all the available patients and all the devices for each patient
from runeq.resources.patient import get_all_patients
patients = get_all_patients()
for patient in patients: 
    print(patient)
    for device in patient.devices: 
        print(' ',device)

Patient(id="rcs07", name="RCS07")
  Device(id="xunPq7qF", name="StriveStudy Left", patient_id="rcs07")
  Device(id="RElEtNme", name="Apple Watch Right (OLD)", patient_id="rcs07")
  Device(id="mn69eHPB", name="Apple Watch Right 011823", patient_id="rcs07")
  Device(id="Ci8uqRFf", name="Strive PD", patient_id="rcs07")
  Device(id="GNmN5Ps_", name="Apple Watch Left 011823", patient_id="rcs07")
  Device(id="0Z48CCdv", name="Apple Watch Left (OLD)", patient_id="rcs07")
  Device(id="476fcJDJ", name="StriveStudy Right", patient_id="rcs07")
  Device(id="EQkHRl_j", name="StriveStudy Left", patient_id="rcs07")
  Device(id="8QuY9OFb", name="Apple Watch Left", patient_id="rcs07")
  Device(id="zfVoAXlX", name="Strive PD Right 01.18.22", patient_id="rcs07")
  Device(id="NPC700403H", name="RC+S Right", patient_id="rcs07")
  Device(id="NPC700419H", name="RC+S Left", patient_id="rcs07")
  Device(id="fn1Ww9vP", name="Strive PD Left 01.18.22", patient_id="rcs07")
  Device(id="Om3Cm3Kz", name="Apple Watch Right", patient_id="rcs07")
  Device(id="U_xlWbXm", name="StriveStudy Left", patient_id="rcs07")

In [4]:
# Get the streams available for a particular patient
from runeq.resources.stream_metadata import get_patient_stream_metadata
patient_id = 'rcs07'
patient_streams = get_patient_stream_metadata(patient_id)
print(f'Found {len(patient_streams)} total streams')
stream_df = patient_streams.to_dataframe()
display(stream_df)

categories = stream_df['category'].unique().tolist()
print(f'Found the following categories of streams: \n  {categories}')

Found 311 total streams

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,category,log_type,measurement,id,severity,axis,source_device,function,hk_aggregation
0,1.677297e+09,ingest-rune-events.0,0Z48CCdv,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.642695e+09,1.645120e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,stop,watch_recording_manual,32bb76f4d67e758a85308fd1fa154f4f88f8cb0d6c0349...,NaN,NaN,NaN,NaN,NaN
1,1.677308e+09,ingest-rune-events.0,0Z48CCdv,rcs07,"{'name': 'Event', 'description': 'Occurrences ...",1.642581e+09,1.645814e+09,"{'category': 'patient_report', 'log_type': 'st...",patient_report,start,watch_recording_manual,2c81d8582eeb3aabcb0efe3af6abc063f7a2b17e9aa674...,NaN,NaN,NaN,NaN,NaN
2,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'none', 'm...",symptom,NaN,tremor,d382ad670ae5c715dd4444b89a6ee808baa93a760e85bc...,none,NaN,NaN,NaN,NaN
3,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'mild', 'm...",symptom,NaN,tremor,f548ba2c90ef848cb609ebc079364c43687f2ca65df9b9...,mild,NaN,NaN,NaN,NaN
4,1.655402e+09,ingest-strive-applewatch-md.0,0Z48CCdv,rcs07,"{'name': 'Duration', 'description': 'Durations...",1.588703e+09,1.645126e+09,"{'category': 'symptom', 'severity': 'unknown',...",symptom,NaN,tremor,44f04f8dc5a93e7878bc6fa06cf0741af808cab52a0b3e...,unknown,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
306,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Rate per minute', 'description': 'Ra...",1.674082e+09,1.688421e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate,72a7f4e117413c6b9fb2d79190b696e9c827ef44d290b3...,NaN,NaN,apple_watch,NaN,NaN
307,1.701264e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Rate per minute', 'description': 'Ra...",1.680200e+09,1.685037e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate_resting,0447d4eed06a581d23727191447e82382fbf03aced07e9...,NaN,NaN,apple_health,NaN,NaN
308,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Speed', 'description': 'Speed, sampl...",1.679622e+09,1.684442e+09,"{'category': 'motion', 'measurement': 'stair_d...",motion,NaN,stair_descent_speed,37ef41600f9da5dbaa0fa17472735397ad5488198bbaf5...,NaN,NaN,apple_health,NaN,NaN
309,1.701264e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'Speed', 'description': 'Speed, sampl...",1.680205e+09,1.684442e+09,"{'category': 'motion', 'measurement': 'stair_a...",motion,NaN,stair_ascent_speed,e1d76e69aac7072b41ec6c9ac6fb2c9391a4bbc7df8aa8...,NaN,NaN,apple_health,NaN,NaN
310,1.701263e+09,ingest-strive-healthkit.1,zfVoAXlX,rcs07,"{'name': 'State', 'description': 'Current stat...",1.674082e+09,1.688421e+09,"{'category': 'vitals', 'measurement': 'heart_r...",vitals,NaN,heart_rate_motion_context,36e919adc4083f5bea6add12ed730c7145febe12892a3e...,NaN,NaN,apple_watch,NaN,NaN

Found the following categories of streams:
  ['patient_report', 'symptom', 'motion', 'vitals', 'device_info']

In [5]:
# Look at the more specific attributes of the motion-related streams
grav_streams = patient_streams.filter(category='motion', measurement='gravity')
display(grav_streams.to_dataframe())

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,axis,category,measurement,id
0,1.650482e+09,ingest-strive-applewatch-motion.0,0Z48CCdv,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.587578e+09,1.645820e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,27c0c60962c7e11fcff89201dbba482b5295afd1d5cef0...
1,1.650482e+09,ingest-strive-applewatch-motion.0,0Z48CCdv,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.587578e+09,1.645820e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,5b8c3617d6cab3e64e91e6c07cfcdc324f2c1af9743790...
2,1.650482e+09,ingest-strive-applewatch-motion.0,0Z48CCdv,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.587578e+09,1.645820e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,36d09ee1e1283aeacdfa93072ce3bbf43eee9184cbf4d3...
3,1.650482e+09,ingest-strive-applewatch-motion.0,8QuY9OFb,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.646083e+09,1.675611e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,90dc82f14f5278e6b053cec09244c79c68ca3ff7786dac...
4,1.650482e+09,ingest-strive-applewatch-motion.0,8QuY9OFb,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.646083e+09,1.675611e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,3fe25a4a3721cae7078a82310c31b2540526c858614484...
5,1.650482e+09,ingest-strive-applewatch-motion.0,8QuY9OFb,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.646083e+09,1.675611e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,b8113f86c843478bafca83cd542b3bcea002b6603f59a7...
6,1.674084e+09,ingest-strive-applewatch-motion.0,GNmN5Ps_,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.684776e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,faac413d766bf0ad5352e30008091ff99feb92bab7e956...
7,1.674084e+09,ingest-strive-applewatch-motion.0,GNmN5Ps_,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.684776e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,9e4797d7d7e5a85ada39133f710848856c9472e4eea0e2...
8,1.674084e+09,ingest-strive-applewatch-motion.0,GNmN5Ps_,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.684776e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,7af3f8f48176c57e932f3d16e460878419faccf61b645b...
9,1.659653e+09,ingest-strive-applewatch-motion.0,Om3Cm3Kz,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.659653e+09,1.675382e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,963904c4b6b323c852afab26b887be791a119dcc1d6819...
10,1.659653e+09,ingest-strive-applewatch-motion.0,Om3Cm3Kz,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.659653e+09,1.675382e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,432dbdc28b2bdb660815b0be88c0b62948a4c4f1ae327d...
11,1.659653e+09,ingest-strive-applewatch-motion.0,Om3Cm3Kz,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.659653e+09,1.675382e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,9130eae8249ff61159f16cf2b1fdecff4f17368a66e527...
12,1.650483e+09,ingest-strive-applewatch-motion.0,RElEtNme,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.594675e+09,1.658984e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,b507f65e9e01d3ac25ecd6f43ff97bca0318dc02f7e1d1...
13,1.650483e+09,ingest-strive-applewatch-motion.0,RElEtNme,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.594675e+09,1.658984e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,60c21dceaabd21f9a1d2bbad8aa72c0c12d07bd64f80f2...
14,1.650483e+09,ingest-strive-applewatch-motion.0,RElEtNme,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.594675e+09,1.658984e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,5d7a9d43b2fd1344788a3d951012b231d30b698e2cd926...
15,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'y', 'category': 'motion', 'measureme...",y,motion,gravity,0dc5b6c50ea389a4d90c6ef88a284f674e37d4d5b6f158...
16,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,gravity,c6dd49ba9bb7c545067bdf55338c0f0694a5229c98330b...
17,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'z', 'category': 'motion', 'measureme...",z,motion,gravity,3edf20fbc7ebd3c5db0fae47abc14e3eb00e9534958cf9...

In [6]:
# Make a function for more customizable filtering of the available streams
from runeq.resources.stream_metadata import get_stream_metadata, get_stream_availability_dataframe
stream_meta = get_stream_metadata(list(grav_streams.ids())[0])

def is_x_stream(stream):
    return 'axis' in stream.parameters.keys() and stream.parameters['axis'] in ['x'] # , 'y', 'z']


x_streams = patient_streams.filter(filter_function=is_x_stream, measurement='user')
display(x_streams.to_dataframe())

# Get available times for May 4, 2023
try:
    available = x_streams.get_batch_availability_dataframe(
        start_time=1683219600, end_time=1683241200, timezone=-28800,
        batch_operation='any', resolution=60*15)
except Exception as e:
    print(e)
else:
    display(available)

,created_at,algorithm,device_id,patient_id,stream_type,min_time,max_time,parameters,axis,category,measurement,id
0,1.650482e+09,ingest-strive-applewatch-motion.0,0Z48CCdv,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.587578e+09,1.645820e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,5905d9dd8f62dc056f6424454e90415bb56a4a0429ab9a...
1,1.650482e+09,ingest-strive-applewatch-motion.0,8QuY9OFb,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.646083e+09,1.675611e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,3a9f0a4553ed4e6db2459bae892b7ce5c5f273ba339b4a...
2,1.674084e+09,ingest-strive-applewatch-motion.0,GNmN5Ps_,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.684776e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,7e50ac9e12101cbe662ec1d1063f51e7b5f1f96fc34d19...
3,1.659653e+09,ingest-strive-applewatch-motion.0,Om3Cm3Kz,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.659653e+09,1.675382e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,20242d79a3ee4fc473783c6dc72411857fea9f467773b0...
4,1.650483e+09,ingest-strive-applewatch-motion.0,RElEtNme,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.594675e+09,1.658984e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,122d0d10679b8e6b794b995addadd2fa854fad86c55949...
5,1.674084e+09,ingest-strive-applewatch-motion.0,mn69eHPB,rcs07,"{'name': 'Acceleration', 'description': 'Accel...",1.674083e+09,1.686704e+09,"{'axis': 'x', 'category': 'motion', 'measureme...",x,motion,user,adb411995e64ec3540e53eba88b566304fe94725296840...

                         time  availability
0   2023-05-04T09:00:00-08:00             0
1   2023-05-04T09:15:00-08:00             1
2   2023-05-04T09:30:00-08:00             1
3   2023-05-04T09:45:00-08:00             1
4   2023-05-04T10:00:00-08:00             1
5   2023-05-04T10:15:00-08:00             1
6   2023-05-04T10:30:00-08:00             1
7   2023-05-04T10:45:00-08:00             1
8   2023-05-04T11:00:00-08:00             1
9   2023-05-04T11:15:00-08:00             1
10  2023-05-04T11:30:00-08:00             1
11  2023-05-04T11:45:00-08:00             1
12  2023-05-04T12:00:00-08:00             1
13  2023-05-04T12:15:00-08:00             1
14  2023-05-04T12:30:00-08:00             1
15  2023-05-04T12:45:00-08:00             1
16  2023-05-04T13:00:00-08:00             1
17  2023-05-04T13:15:00-08:00             1
18  2023-05-04T13:30:00-08:00             1
19  2023-05-04T13:45:00-08:00             1
20  2023-05-04T14:00:00-08:00             1
21  2023-05-04T14:15:00-08:00             1
22  2023-05-04T14:30:00-08:00             1
23  2023-05-04T14:45:00-08:00             1

In [16]:
import numpy as np
from runeq.resources.patient import get_device
# Get a list of devices with data available on a given day:
date = pd.Timestamp(1681369200, unit='s', tz='US/Pacific')
end_of_day = date + pd.Timedelta(days=5)

cumulative_avail = {}
for device in patient_streams.to_dataframe()['device_id'].unique():
    device_streams = x_streams.filter(device_id=device)
    try:
        device_avail = device_streams.get_batch_availability_dataframe(
            start_time=int(date.timestamp()), end_time=int(end_of_day.timestamp()), timezone=-28800,
            resolution=60*60, batch_operation='any'
        )
    except Exception as e:
        print(f'Device {device}')
        print(f'    {e}')
    else:
        # There is some data available for this device
        if sum(device_avail['availability']) > 0:
            print(f'Found data for {device}: {get_device(patient, device).name}')
            cumulative_avail[device] = device_avail
        else:
            print(f'No data for {device}')

No data for 0Z48CCdv
Device 476fcJDJ
    400 : {'message': 'no stream ids found in request', 'type': ''}
No data for 8QuY9OFb
Device Ci8uqRFf
    400 : {'message': 'no stream ids found in request', 'type': ''}
Found data for GNmN5Ps_: Apple Watch Left 011823
No data for Om3Cm3Kz
No data for RElEtNme
Device U_xlWbXm
    400 : {'message': 'no stream ids found in request', 'type': ''}
Device fn1Ww9vP
    400 : {'message': 'no stream ids found in request', 'type': ''}
Found data for mn69eHPB: Apple Watch Right 011823
Device xunPq7qF
    400 : {'message': 'no stream ids found in request', 'type': ''}
Device zfVoAXlX
    400 : {'message': 'no stream ids found in request', 'type': ''}

In [17]:
# Given the devices from above, find the range of times with available data
if len(cumulative_avail):
    devices = list(cumulative_avail.keys())
    raw_avail = [df['availability'].to_numpy() for df in cumulative_avail.values()]
    cumulative = [np.sum(raw_avail, axis=0) >= 1][0]
    avail_times = (cumulative_avail[devices[0]]['time'][cumulative]).to_numpy()
    start, end = int(pd.Timestamp(avail_times[0]).timestamp()), int(pd.Timestamp(avail_times[-1]).timestamp())
    print(f'Data available between {start} and {end}')
else:
    print('NO DATA FOUND IN THE GIVEN TIME RANGE!')

Data available between 1681408800 and 1681545600

In [19]:
# Get the data for the available time range
desired_ids = devices

def match_devices(stream):
    return 'device_id' in stream.parameters and stream.parameters['device_id'] in desired_ids

desired_streams = patient_streams.filter(category='motion', filter_function=match_devices)
desired_streams.get_stream_dataframe(
    start_time=start, end_time=end
)

ValueError: No objects to concatenate